[package]
name = "getting-started"
version = "0.1.0"
authors = ["Tej Babu Balireddi <tejbabu91@gmail.com>"]

[[bin]]
name = "spinning-square"
path = "src/main.rs"

[dependencies]
piston = "0.36.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.46.0"
piston2d-opengl_graphics = "0.53.0"
